# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: key_transaction.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='key_transaction.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x15key_transaction.proto\")\n\x06\x41\x64\x64Key\x12\x0e\n\x06key_id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\tb\x06proto3')
)




_ADDKEY = _descriptor.Descriptor(
  name='AddKey',
  full_name='AddKey',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key_id', full_name='AddKey.key_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='user_id', full_name='AddKey.user_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=66,
)

DESCRIPTOR.message_types_by_name['AddKey'] = _ADDKEY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AddKey = _reflection.GeneratedProtocolMessageType('AddKey', (_message.Message,), dict(
  DESCRIPTOR = _ADDKEY,
  __module__ = 'key_transaction_pb2'
  # @@protoc_insertion_point(class_scope:AddKey)
  ))
_sym_db.RegisterMessage(AddKey)


# @@protoc_insertion_point(module_scope)
