# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: relationship_state.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='relationship_state.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x18relationship_state.proto\"=\n\x15RelationshipContainer\x12$\n\rrelationships\x18\x01 \x03(\x0b\x32\r.Relationship\"5\n\x0cRelationship\x12\x11\n\tobject_id\x18\x01 \x01(\t\x12\x12\n\nrelated_id\x18\x02 \x01(\tb\x06proto3')
)




_RELATIONSHIPCONTAINER = _descriptor.Descriptor(
  name='RelationshipContainer',
  full_name='RelationshipContainer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='relationships', full_name='RelationshipContainer.relationships', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=89,
)


_RELATIONSHIP = _descriptor.Descriptor(
  name='Relationship',
  full_name='Relationship',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='object_id', full_name='Relationship.object_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='related_id', full_name='Relationship.related_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=91,
  serialized_end=144,
)

_RELATIONSHIPCONTAINER.fields_by_name['relationships'].message_type = _RELATIONSHIP
DESCRIPTOR.message_types_by_name['RelationshipContainer'] = _RELATIONSHIPCONTAINER
DESCRIPTOR.message_types_by_name['Relationship'] = _RELATIONSHIP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RelationshipContainer = _reflection.GeneratedProtocolMessageType('RelationshipContainer', (_message.Message,), dict(
  DESCRIPTOR = _RELATIONSHIPCONTAINER,
  __module__ = 'relationship_state_pb2'
  # @@protoc_insertion_point(class_scope:RelationshipContainer)
  ))
_sym_db.RegisterMessage(RelationshipContainer)

Relationship = _reflection.GeneratedProtocolMessageType('Relationship', (_message.Message,), dict(
  DESCRIPTOR = _RELATIONSHIP,
  __module__ = 'relationship_state_pb2'
  # @@protoc_insertion_point(class_scope:Relationship)
  ))
_sym_db.RegisterMessage(Relationship)


# @@protoc_insertion_point(module_scope)
