# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: role_state.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='role_state.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x10role_state.proto\"C\n\x17RoleAttributesContainer\x12(\n\x0frole_attributes\x18\x01 \x03(\x0b\x32\x0f.RoleAttributes\"A\n\x0eRoleAttributes\x12\x0f\n\x07role_id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x10\n\x08metadata\x18\x03 \x01(\t\"E\n\x19RoleRelationshipContainer\x12(\n\rrelationships\x18\x01 \x03(\x0b\x32\x11.RoleRelationship\"8\n\x10RoleRelationship\x12\x0f\n\x07role_id\x18\x01 \x01(\t\x12\x13\n\x0bidentifiers\x18\x02 \x03(\tb\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_ROLEATTRIBUTESCONTAINER = _descriptor.Descriptor(
  name='RoleAttributesContainer',
  full_name='RoleAttributesContainer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='role_attributes', full_name='RoleAttributesContainer.role_attributes', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=87,
)


_ROLEATTRIBUTES = _descriptor.Descriptor(
  name='RoleAttributes',
  full_name='RoleAttributes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='role_id', full_name='RoleAttributes.role_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='RoleAttributes.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='metadata', full_name='RoleAttributes.metadata', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=89,
  serialized_end=154,
)


_ROLERELATIONSHIPCONTAINER = _descriptor.Descriptor(
  name='RoleRelationshipContainer',
  full_name='RoleRelationshipContainer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='relationships', full_name='RoleRelationshipContainer.relationships', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=156,
  serialized_end=225,
)


_ROLERELATIONSHIP = _descriptor.Descriptor(
  name='RoleRelationship',
  full_name='RoleRelationship',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='role_id', full_name='RoleRelationship.role_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='identifiers', full_name='RoleRelationship.identifiers', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=227,
  serialized_end=283,
)

_ROLEATTRIBUTESCONTAINER.fields_by_name['role_attributes'].message_type = _ROLEATTRIBUTES
_ROLERELATIONSHIPCONTAINER.fields_by_name['relationships'].message_type = _ROLERELATIONSHIP
DESCRIPTOR.message_types_by_name['RoleAttributesContainer'] = _ROLEATTRIBUTESCONTAINER
DESCRIPTOR.message_types_by_name['RoleAttributes'] = _ROLEATTRIBUTES
DESCRIPTOR.message_types_by_name['RoleRelationshipContainer'] = _ROLERELATIONSHIPCONTAINER
DESCRIPTOR.message_types_by_name['RoleRelationship'] = _ROLERELATIONSHIP

RoleAttributesContainer = _reflection.GeneratedProtocolMessageType('RoleAttributesContainer', (_message.Message,), dict(
  DESCRIPTOR = _ROLEATTRIBUTESCONTAINER,
  __module__ = 'role_state_pb2'
  # @@protoc_insertion_point(class_scope:RoleAttributesContainer)
  ))
_sym_db.RegisterMessage(RoleAttributesContainer)

RoleAttributes = _reflection.GeneratedProtocolMessageType('RoleAttributes', (_message.Message,), dict(
  DESCRIPTOR = _ROLEATTRIBUTES,
  __module__ = 'role_state_pb2'
  # @@protoc_insertion_point(class_scope:RoleAttributes)
  ))
_sym_db.RegisterMessage(RoleAttributes)

RoleRelationshipContainer = _reflection.GeneratedProtocolMessageType('RoleRelationshipContainer', (_message.Message,), dict(
  DESCRIPTOR = _ROLERELATIONSHIPCONTAINER,
  __module__ = 'role_state_pb2'
  # @@protoc_insertion_point(class_scope:RoleRelationshipContainer)
  ))
_sym_db.RegisterMessage(RoleRelationshipContainer)

RoleRelationship = _reflection.GeneratedProtocolMessageType('RoleRelationship', (_message.Message,), dict(
  DESCRIPTOR = _ROLERELATIONSHIP,
  __module__ = 'role_state_pb2'
  # @@protoc_insertion_point(class_scope:RoleRelationship)
  ))
_sym_db.RegisterMessage(RoleRelationship)


# @@protoc_insertion_point(module_scope)
