jobs:
  include:
    - stage: backend
      language: python
      python:
        - "3.6"
      script:
        - pytest --ignore=tests

    - stage: frontend
      language: node_js
      node_js:
        - "lts/*"
      before_install:
        - cd ./client
      install:
        - npm install
      script:
        - npm test
