# Copyright 2019 Contributors to Hyperledger Sawtooth
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ------------------------------------------------------------------------------

version: "3"

services:
  rbac-server:
    build:
      context: .
      dockerfile: ./docker/rbac.server.Dockerfile
    container_name: rbac-server
    image: rbac-server:${ISOLATION_ID-latest}
    volumes:
      - ".:/project/hyperledger-rbac"
    ports:
      - "8000:8000"
    depends_on:
      - ledger-sync
      - rethink
      - validator
    environment:
      - AES_KEY=${AES_KEY}
      - DB_HOST=${DB_HOST:-rethink}
      - DB_PORT=${DB_PORT:-28015}
      - DB_NAME=${DB_NAME:-rbac}
      - ENABLE_AZURE_SYNC=${ENABLE_AZURE_SYNC:-1}
      - ENABLE_LDAP_SYNC=${ENABLE_LDAP_SYNC:-1}
      - ENABLE_NEXT_BASE_USE=${ENABLE_NEXT_BASE_USE:-1}
      - LDAP_DC=DC=AD2012,DC=LAB
      - LDAP_SERVER=my_fake_server
      - LOGGING_LEVEL=${LOGGING_LEVEL:-INFO}
      - NEXT_ADMIN_NAME=${NEXT_ADMIN_NAME:-Admin}
      - NEXT_ADMIN_USER=${NEXT_ADMIN_USER:-Admin}
      - NEXT_ADMIN_PASS=${NEXT_ADMIN_PASS:-p@ssw0rd123}
      - NEXT_ADMIN_EMAIL=${NEXT_ADMIN_EMAIL:-admin@test.com}
      - SECRET_KEY=${SECRET_KEY}
      - SERVER_HOST=${SERVER_HOST:-0.0.0.0}
      - SERVER_PORT=${SERVER_PORT:-8000}
      - TENANT_ID=${TENANT_ID}
    command: ./bin/rbac-server --db-host rethink --validator-host validator

  rethink:
    container_name: rbac-rethink
    image: rethinkdb:2.3
    ports:
      - "9090:8080"
    expose:
       - "28015"

  rbac-tp:
    build:
      context: .
      dockerfile: ./docker/rbac.processor.Dockerfile
    container_name: rbac-tp
    image: rbac-tp:${ISOLATION_ID-latest}
    volumes:
      - ".:/project/hyperledger-rbac"
    environment:
      - LOGGING_LEVEL=${LOGGING_LEVEL:-INFO}
      - HOST=${HOST:-localhost}
    command: ./bin/rbac-tp tcp://validator:4004

  ledger-sync:
    build:
      context: .
      dockerfile: ./docker/rbac.ledger_sync.Dockerfile
    container_name: rbac-ledger-sync
    image: rbac-ledger-sync:${ISOLATION_ID-latest}
    volumes:
      - ".:/project/hyperledger-rbac"
    depends_on:
      - rethink
      - validator
    environment:
      - LOGGING_LEVEL=${LOGGING_LEVEL:-INFO}
      - HOST=${HOST:-localhost}
      - AES_KEY=${AES_KEY}
    command: |
      bash -c "
        ./bin/setup_db --host rethink &&
        ./bin/rbac-ledger-sync --db-host rethink --validator tcp://validator:4004
      \"\""

  rest-api:
    container_name: sawtooth-rest-api
    image: hyperledger/sawtooth-rest-api:1.0
    ports:
      - "8008:8008"
    depends_on:
      - validator
    command: sawtooth-rest-api --connect tcp://validator:4004 --bind rest-api:8008

  settings-tp:
    container_name: rbac-settings-tp
    image: hyperledger/sawtooth-settings-tp:1.0
    depends_on:
      - validator
    command: settings-tp --connect tcp://validator:4004

  validator:
    container_name: rbac-validator-tp
    image: hyperledger/sawtooth-validator:1.0
    entrypoint: |
      bash -c "
        if [ ! -f /etc/sawtooth/keys/validator.priv ]; then
          sawadm keygen &&
          sawtooth keygen my_key &&
          sawset genesis -k /root/.sawtooth/keys/my_key.priv &&
          sawadm genesis config-genesis.batch
        fi;
        sawtooth-validator \
          --endpoint tcp://validator:8800 \
          --bind component:tcp://eth0:4004 \
          --bind network:tcp://eth0:8800
          --scheduler parallel
      \"\""

  test-runner:
    build:
      context: .
      dockerfile: ./docker/tests.Dockerfile
    image: rbac-shell:${ISOLATION_ID-latest}
    volumes:
      - ".:/project/hyperledger-rbac"
    command: pytest
    environment:
      - LOGGING_LEVEL=${LOGGING_LEVEL:-INFO}
      - PYTHONPATH=/project/hyperledger-rbac/
      - HOST=${HOST:-localhost}
      - LDAP_SERVER=${LDAP_SERVER}
