#!/bin/bash

# Copyright 2018 Contributors to Hyperledger Sawtooth
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# -----------------------------------------------------------------------------

MODELS_DIR=chatbot/models/current
CONFIG_DIR=chatbot/config

python -m rasa_core.run --enable_api --port 5005 \
    --credentials $CONFIG_DIR/credentials.yml \
    --endpoints $CONFIG_DIR/endpoints.yml \
    -d $MODELS_DIR/core \
    -u $MODELS_DIR/nlu
