parameters:
      - $ref: '#/parameters/taskId'
    post:
      security:
        - Bearer: []
      description: Add an administrator to a particular task
      parameters:
        - name: administrator
          in: body
          description: User to be added as an administrator to the task
          required: true
          schema:
            type: object
            properties:
              id:
                type: string
                description: Id of the user to add as an administrator
      responses:
        '200':
          description: Success response with proposal id
          schema:
            $ref: '#/definitions/proposalId'
        '400':
          description: Response for a bad request
          schema:
            $ref: '#/definitions/400Error'
        '401':
          description: Response for an unauthorized request
          schema:
            $ref: '#/definitions/401Error'
        '403':
          description: Response for a forbidden request
          schema:
            $ref: '#/definitions/403Error'
        '404':
          description: Response for object not found
          schema:
            $ref: '#/definitions/404Error'
        '503':
          description: Response for an internal unknown error
          schema:
            $ref: '#/definitions/503Error'
        default:
          description: Response for an unexpected error
          schema:
            $ref: '#/definitions/error'
    delete:
      security:
        - Bearer: []
      description: Remove an administrator from a particular task
      parameters:
        - name: administrator
          in: body
          description: User to be removed from the task's administrator list
          required: true
          schema:
            type: object
            properties:
              id:
                type: string
                description: Id of the user to remove as an administrator
      responses:
        '200':
          description: Success response with proposal id
          schema:
            $ref: '#/definitions/proposalId'
        '400':
          description: Response for a bad request
          schema:
            $ref: '#/definitions/400Error'
        '401':
          description: Response for an unauthorized request
          schema:
            $ref: '#/definitions/401Error'
        '403':
          description: Response for a forbidden request
          schema:
            $ref: '#/definitions/403Error'
        '404':
          description: Response for object not found
          schema:
            $ref: '#/definitions/404Error'
        '503':
          description: Response for an internal unknown error
          schema:
            $ref: '#/definitions/503Error'
        default:
          description: Response for an unexpected error
          schema:
            $ref: '#/definitions/error'