    get:
      security:
        - Bearer: []
      description: Fetches the complete details of all roles in state
      parameters:
        - $ref: '../parameters/parameters.yaml#/head'
        - $ref: '../parameters/parameters.yaml#/start'
        - $ref: '../parameters/parameters.yaml#/limit'
      responses:
        '200':
          description: Response with a list of roles
          schema:
            properties:
              link:
                $ref: '../definitions/definitions.yaml#/getAllRolesLink'
              paging:
                $ref: '../definitions/definitions.yaml#/paging'
              head:
                $ref: '../definitions/definitions.yaml#/head'
              data:
                type: array
                items:
                  $ref: '../definitions/definitions.yaml#/role'
        '400':
          description: Response for a bad request
          schema:
            $ref: '../definitions/definitions.yaml#/400Error'
        '401':
          description: Response for an unauthorized request
          schema:
            $ref: '../definitions/definitions.yaml#/401Error'
        '403':
          description: Response for a forbidden request
          schema:
            $ref: '../definitions/definitions.yaml#/403Error'
        '503':
          description: Response for an internal unknown error
          schema:
            $ref: '../definitions/definitions.yaml#/503Error'
        default:
          description: Response for an unexpected error
          schema:
            $ref: '../definitions/definitions.yaml#/error'
    post:
      security:
        - Bearer: []
      description: Creates a new role in the system
      parameters:
        - name: role
          in: body
          description: Role to add to the system
          required: true
          schema:
            $ref: '../definitions/definitions.yaml#/newRole'
      responses:
        '200':
          description: Success response with role resource
          schema:
            properties:
              data:
                $ref: '../definitions/definitions.yaml#/newRoleResponse'
        '400':
          description: Response for a bad request
          schema:
            $ref: '../definitions/definitions.yaml#/400Error'
        '401':
          description: Response for an unauthorized request
          schema:
            $ref: '../definitions/definitions.yaml#/401Error'
        '403':
          description: Response for a forbidden request
          schema:
            $ref: '../definitions/definitions.yaml#/403Error'
        '404':
          description: Response for object not found
          schema:
            $ref: '../definitions/definitions.yaml#/404Error'
        '503':
          description: Response for an internal unknown error
          schema:
            $ref: '../definitions/definitions.yaml#/503Error'
        default:
          description: Response for an unexpected error
          schema:
            $ref: '../definitions/definitions.yaml#/error'
