get:
      security:
        - Bearer: []
      description: Fetches the complete details of all roles in state
      parameters:
        - $ref: '#/parameters/head'
        - $ref: '#/parameters/start'
        - $ref: '#/parameters/limit'
      responses:
        '200':
          description: Response with a list of roles
          schema:
            properties:
              link:
                $ref: '#/definitions/getAllRolesLink'
              paging:
                $ref: '#/definitions/paging'
              head:
                $ref: '#/definitions/head'
              data:
                type: array
                items:
                  $ref: '#/definitions/role'
        '400':
          description: Response for a bad request
          schema:
            $ref: '#/definitions/400Error'
        '401':
          description: Response for an unauthorized request
          schema:
            $ref: '#/definitions/401Error'
        '403':
          description: Response for a forbidden request
          schema:
            $ref: '#/definitions/403Error'
        '503':
          description: Response for an internal unknown error
          schema:
            $ref: '#/definitions/503Error'
        default:
          description: Response for an unexpected error
          schema:
            $ref: '#/definitions/error'
    post:
      security:
        - Bearer: []
      description: Creates a new role in the system
      parameters:
        - name: role
          in: body
          description: Role to add to the system
          required: true
          schema:
            $ref: '#/definitions/newRole'
      responses:
        '200':
          description: Success response with role resource
          schema:
            properties:
              data:
                $ref: '#/definitions/newRoleResponse'
        '400':
          description: Response for a bad request
          schema:
            $ref: '#/definitions/400Error'
        '401':
          description: Response for an unauthorized request
          schema:
            $ref: '#/definitions/401Error'
        '403':
          description: Response for a forbidden request
          schema:
            $ref: '#/definitions/403Error'
        '404':
          description: Response for object not found
          schema:
            $ref: '#/definitions/404Error'
        '503':
          description: Response for an internal unknown error
          schema:
            $ref: '#/definitions/503Error'
        default:
          description: Response for an unexpected error
          schema:
            $ref: '#/definitions/error'
  '/roles/{id}':
    parameters:
      - $ref: '#/parameters/roleId'
    get:
      security:
        - Bearer: []
      description: Fetches the complete details of a role
      parameters:
        - $ref: '#/parameters/head'
      responses:
        '200':
          description: Response with the fetched role
          schema:
            properties:
              link:
                $ref: '#/definitions/getRoleLink'
              head:
                $ref: '#/definitions/head'
              data:
                $ref: '#/definitions/role'
        '400':
          description: Response for a bad request
          schema:
            $ref: '#/definitions/400Error'
        '401':
          description: Response for an unauthorized request
          schema:
            $ref: '#/definitions/401Error'
        '403':
          description: Response for a forbidden request
          schema:
            $ref: '#/definitions/403Error'
        '404':
          description: Response for object not found
          schema:
            $ref: '#/definitions/404Error'
        '503':
          description: Response for an internal unknown error
          schema:
            $ref: '#/definitions/503Error'
        default:
          description: Response for an unexpected error
          schema:
            $ref: '#/definitions/error'